#!/bin/bash

if [ $EUID = 0 ]; then
  echo "====================================="
  echo "Please do not run this script as Sudo"
  echo "====================================="
  exit
fi

sudo mkdir $HOME/lemontemp/
cd $HOME/lemontemp/

echo "|| Installing package managers ||"

echo "|| Flatpak ||"
sudo apt install flatpak

sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

echo "|| Installing utilities ||"

echo "|| Git, wget, curl, make ||"
sudo apt install git wget curl make

# echo "|| Nvidia drivers ||"
# sudo ...

echo "|| Scrot ||"
sudo apt install scrot

echo "|| Installing apps ||"

echo "|| Firefox ||"
sudo apt install firefox-esr

echo "|| Htop ||"
sudo apt install htop

echo "|| Neofetch ||"
sudo apt install neofetch

echo "|| Gparted ||"
sudo apt install gparted

echo "|| VLC ||"
sudo apt install vlc

echo "|| Spotify ||"
flatpak install flathub com.spotify.Client

echo "|| Discord ||"
flatpak install flathub com.discordapp.Discord

echo "|| Steam ||"
flatpak install flathub com.valvesoftware.Steam

sudo rm -r $HOME/lemontemp/

echo "|| Restarting ||"
while true; do
  read -p "Do you want to restart now? [Y/n]" yn
  case $yn in
    [Yy]* ) sudo shutdown -r now;;
    [Nn]* ) exit;break;;
    "" ) sudo shutdown -r now;;
    * ) echo "Invalid response";;
  esac
done
