#!/bin/bash

if [ $EUID = 0 ]; then
  echo "====================================="
  echo "Please do not run this script as Sudo"
  echo "====================================="
  exit
fi

PS3="Choose apps for an environment"
select opt in "WM" "DE" "Server" "Quit"; do
  case $opt in
    "WM")
      echo "WM apps"
      bash ZZZ1.sh
      ;;
    "DE")
      echo "DE apps"
      bash ZZZ2.sh
      ;;
    "Server")
      echo "Server utilities"
      bash server/appsserver.sh
      ;;
    "Quit")
      break
      ;;
    *)
      echo "Invalid"
      ;;
  esac
  break
done
