#!/usr/bin/env bash

if [ $EUID = 0 ]; then
  echo "====================================="
  echo "Please do not run this script as Sudo"
  echo "====================================="
  exit
fi

sudo mkdir $HOME/lemontemp/
pushd $HOME/lemontemp/

sudo apt install -y git unzip tar

echo "|| Getting dotfiles ||"
sudo git clone https://github.com/PassiveLemon/lemondots/

cp -r lemondots/* $HOME/
rm $HOME/LICENSE
rm $HOME/README.md

echo "|| Extracting archives ||"
cd $HOME/.icons/
sudo unzip kora_*.zip
sudo tar xvzf volantes*.tar.gz

sudo rm *.zip *.tar.gz

cd $HOME/.themes/
sudo tar -xf nordic-darker*.tar.xz

sudo rm *.tar.xz

sudo rm -r $HOME/lemontemp/

echo "|| Changing permissions ||"
sudo chmod u+x $HOME/.xinitrc
sudo chmod u+x $HOME/.config/bspwm/bspwmrc
sudo chmod u+x $HOME/.config/bspwm/bspwmrc
popd
