#!/bin/bash

if [ $EUID = 0 ]; then
  echo "====================================="
  echo "Please do not run this script as Sudo"
  echo "====================================="
  exit
fi

echo "|| Setting up system ||"

# Sudo
echo "|| Sudo ||"
sudo apt install sudo
sudo rm -f /etc/sudoers
sudo cp main/sudoers /etc/
sudo usermod -aG sudo lemon
# If you aren't me, "lemon" with your user account. Don't forget to modify the suoders file in main/configs/.

# Internet configs
echo "|| Internet configs ||"
sudo rm -f /etc/network/interfaces
sudo cp main/interfaces /etc/network/

sudo rm -f /etc/NetworkManager/NetworkManager.conf
sudo cp main/NetworkManager.config /etc/NetworkManager/

# Sources
echo "|| Sources ||"
sudo rm -f /etc/apt/sources.list
sudo cp main/sources.list /etc/apt/

# echo "Changing swap space"

# Change swap space
#	 swapon --show
#	 ls /swapfile
#	 swapoff /swapfile
#	 fallocate -l 4G /swapfile
#	 mkswap /swapfile
#	 swapon /swapfile

# echo "Swap space changed"
echo "|| System setup ||"
echo "|| Restarting ||"

while true; do
  read -p "Do you want to restart now? [Y/n]" yn
  case $yn in
    [Yy]* ) sudo shutdown -r now;;
    [Nn]* ) exit;break;;
    "" ) sudo shutdown -r now;;
    * ) echo "Invalid response";;
  esac
done
