#!/bin/bash

echo "Installing dos2unix"
sudo apt update && sudo apt upgrade
sudo apt install dos2unix

sudo dos2unix syschoose
sudo dos2unix appschoose

if [ $EUID = 0 ]; then
  echo "====================================="
  echo "Please do not run this script as Sudo"
  echo "====================================="
  exit
fi

PS3="Choose an environment"
select opt in "Bspwm - WM" "Gnome - DE" "Xfce - DE" "Quit"; do
  case $opt in
    "Bspwm - DE")
      echo "Bspwm selected"
      bash bspwm/scriptbspwm
      ;;
    "Gnome - WM")
      echo "Gnome selected"
      #bash gnome/scriptgnome
      ;;
    "Xfce - WM")
      echo "WM selected"
      #bash Xfce/scriptxfce
      ;;
    "Server - HL")
      echo "Headless server selected"
      #bash server/scriptserver
      ;;
    "Quit")
      break
      ;;
    *)
      echo "Invalid option"
      ;;
  esac
  break
done
