#!/bin/bash

sudo apt update && sudo apt upgrade
sudo apt install dos2unix

sudo dos2unix syschoose.sh
sudo dos2unix appschoose.sh
sudo dos2unix XXX*.sh
sudo dos2unix ZZZ*.sh

if [ $EUID = 0 ]; then
  echo "====================================="
  echo "Please do not run this script as Sudo"
  echo "====================================="
  exit
fi

PS3="Choose an environment"
select opt in "WM" "DE" "Quit"; do
  case $opt in
    "WM")
      echo "WM selected"
      bash XXX1
      ;;
    "DE")
      echo "DE selected"
      bash XXX2
      ;;
    "Server")
      echo "Server selected"
      #bash server/scriptserver
      ;;
    "Quit")
      break
      ;;
    *)
      echo "Invalid option"
      ;;
  esac
  break
done
