#!/bin/bash

if [ $EUID = 0 ]; then
  echo "====================================="
  echo "Please do not run this script as Sudo"
  echo "====================================="
  exit
fi

echo "|| Installing components ||"

sudo apt install xorg bspwm sxhkd kitty rofi polybar feh psmisc alsa-utils network-manager
sudo alsactl init

echo "|| Ly ||"
sudo apt install build-essential libpam0g-dev libxcb-xkb-dev git
sudo git clone --recurse-submodules https://github.com/cylgom/ly.git
cd ly
sudo make
sudo make install
sudo systemctl enable ly.service
cd ..
sudo rm -r ly

echp "|| Picom Fork ||"
sudo apt install ninja-build gcc meson python3 libxext-dev libxcb1-dev libxcb-damage0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-randr0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-present-dev libxcb-xinerama0-dev libxcb-glx0-dev libpixman-1-dev libdbus-1-dev libconfig-dev libgl1-mesa-dev libpcre2-dev libpcre3-dev libevdev-dev uthash-dev libev-dev libx11-xcb-dev
sudo git clone https://github.com/ibhagwan/picom
cd picom
sudo git submodule update --init --recursive
sudo meson --buildtype=release . build
sudo ninja -C build
sudo ninja -C build install
cd ..
sudo rm -r picom

echo "|| Components installed ||"
echo "|| Configurations selection ||"

while true; do
  read -p "Do you want to install my dotfiles? [Y/n]" yn
  case $yn in
    [Yy]* ) bash bspwm/2lemondots;;
    [Nn]* ) break;;
    "" ) bash bspwm/2lemondots;;
    * ) echo "Invalid response";;
  esac
  break
done

echo "|| Configurations selected ||"
echo "|| Programs selection ||"

while true; do
  read -p "Do you want to install my programs? [Y/n]" yn
  case $yn in
    [Yy]* ) bash bspwm/3apps;;
    [Nn]* ) break;;
    "" ) bash bspwm/3apps;;
    * ) echo "Invalid response";;
  esac
  break
done

echo "|| Programs selected ||"
echo "|| Restart ||"

while true; do
  read -p "Do you want to restart now? [Y/n]" yn
  case $yn in
    [Yy]* ) sudo shutdown -r now;;
    [Nn]* ) break;;
    "" ) sudo shutdown -r now;;
    * ) echo "Invalid response";;
  esac
  break
done
