#!/bin/bash

if [ $EUID = 0 ]; then
  echo "====================================="
  echo "Please do not run this script as Sudo"
  echo "====================================="
  exit
fi

sudo apt install git

sudo git clone https://github.com/PassiveLemon/lemondots/

cp -r lemondots/.config/ $HOME/
cp -r lemondots/.fonts/ $HOME/
cp -r lemondots/.icons/ $HOME/
cp -r lemondots/.wallpapers/ $HOME/
cp lemondots/.xinitrc $HOME/
cp lemondots/.Xresources $HOME/

sudo rm -r lemondots/
