#!/bin/bash

if [ $EUID = 0 ]; then
  echo "====================================="
  echo "Please do not run this script as Sudo"
  echo "====================================="
  exit
fi

sudo apt install git

sudo git clone https://github.com/PassiveLemon/lemondots/

cp -r lemondots/.config/ ~/
cp -r lemondots/.fonts/ ~/
cp lemondots/.xinitrc ~/

sudo rm -r lemondots/

sudo git clone https://github.com/PassiveLemon/lemonwallpapers/

mkdir -p ~/Pictures/
cp -r lemonwallpapers/wallpapers/ ~/Pictures/

sudo rm -r lemonwallpapers/
