#!/bin/bash

if [ $EUID = 0 ]; then
  echo "====================================="
  echo "Please do not run this script as Sudo"
  echo "====================================="
  exit
fi

sudo apt install git

sudo git clone https://github.com/PassiveLemon/lemondots/

sudo dpkg -i lemondots/lightdm/lightdm-webkit2-greeter_2.2.5-1+15.8_amd64.deb
sudo apt -f install

sudo rm -rf /usr/share/lightdm-webkit/themes/minimal/
sudo mkdir -p /usr/share/lightdm-webkit/themes/
sudo cp -r lemondots/lightdm/minimal /usr/share/lightdm-webkit/themes/

sudo rm -f /etc/lightdm/lightdm.conf
sudo rm -f /etc/lightdm/lightdm-webkit2-greeter.conf
sudo cp lemondots/lightdm/lightdm.conf /etc/lightdm/
sudo cp lemondots/lightdm/lightdm-webkit2-greeter.conf /etc/lightdm/

cp -r lemondots/.config/ ~/
cp -r lemondots/.fonts/ ~/
cp lemondots/.xinitrc ~/

sudo rm -r lemondots/

sudo git clone https://github.com/PassiveLemon/lemonwallpapers/

mkdir -p ~/Pictures/
cp -r lemonwallpapers/wallpapers/ ~/Pictures/

sudo rm -r lemonwallpapers/
