#!/bin/bash

if [ $EUID = 0 ]; then
  echo "====================================="
  echo "Please do not run this script as Sudo"
  echo "====================================="
  exit
fi

echo "|| Installing components ||"

sudo apt install xorg bspwm sxhkd kitty rofi polybar picom feh psmisc alsa-utils network-manager &&
sudo alsactl init

sudo apt install build-essential libpam0g-dev libxcb-xkb-dev git
sudo git clone --recurse-submodules https://github.com/cylgom/ly.git
cd ly
sudo make
sudo make install
sudo systemctl enable ly.service
cd ..
sudo rm -r ly

echo "|| Components installed ||"
echo "|| Configurations selection ||"

while true; do
  read -p "Do you want to install my dotfiles? [Y/n]" yn
  case $yn in
    [Yy]* ) bash bspwm/lemondotsbspwm;;
    [Nn]* ) break;;
    "" ) bash bspwm/lemondotsbspwm;;
    * ) echo "Invalid response";;
  esac
  break
done

echo "|| Configurations selected ||"
echo "|| Programs selection ||"

while true; do
  read -p "Do you want to install my programs? [Y/n]" yn
  case $yn in
    [Yy]* ) bash bspwm/appsbspwm;;
    [Nn]* ) break;;
    "" ) bash bspwm/appsbspwm;;
    * ) echo "Invalid response";;
  esac
  break
done

echo "|| Programs selected ||"
echo "|| Restart ||"

while true; do
  read -p "Do you want to restart now? [Y/n]" yn
  case $yn in
    [Yy]* ) sudo shutdown -r now;;
    [Nn]* ) break;;
    "" ) sudo shutdown -r now;;
    * ) echo "Invalid response";;
  esac
  break
done
